/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaCaixaView;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import model.*;
import java.util.List;
import javax.swing.JList;

/**
 *
 * @author internet
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public  Menu menu;
    public CadastroUsuario cadUser;
    public ListaProdutos listaProd;
    public CadastroProduto cadProd;
    
    public Login() {
        initComponents();
                this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
               // login_.setSize(300,300);
                this.setLocationRelativeTo(null);
                this.setTitle("Gestão de Produtos");
                this.setVisible(true);
                
                cadUser = new CadastroUsuario();
                menu = new Menu();
                listaProd = new ListaProdutos();
                cadProd = new CadastroProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        jButton1.setText("Entrar");

        jButton2.setText("Configurações");

        jButton3.setText("Sair");
        jButton3.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel3.setText("Controle de Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
/**/
 public JButton getButton(){
     return jButton1;
 } 
 public String getLogin(){
     return jTextField1.getText();
 }
 public  String getSenha(){
     return jPasswordField1.getText();
 }
 public JButton getButtonLogout(){
     return menu.getButtonLogout();
 }
 public JButton getButtonListaProdutos(){
     return menu.getButtonListaProdutos();
 }
 public JList getJListProdutos(){
     return listaProd.getJListProdutos();
 }
 public JButton getButtonCadastraProduto(){
     return menu.getButtonCadastraProduto();
 }
 public void showListaProdutos(List<Produto> prodList){
    listaProd.setLocationRelativeTo(null);
    listaProd.setVisible(true);
    listaProd.showAllProdutos(prodList);
 }
 public void showMenu(){
    
    this.setVisible(false);
    //menu.setSize(300,300);
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);
    
 }
  public void showCadastroUsuario(){
        cadUser.setLocationRelativeTo(null);
        cadUser.setVisible(true);
  }
  
 public JButton getButtonCadastro(){
     return menu.getButtonCadastroUsuario();
 }
 public JButton getButtonCadastraClicked(){
     return cadProd.getCadastraButton();
 }
 
 public Produto getProdutoInsert(){
     CadastroSucessoDialog cadOK = new CadastroSucessoDialog();
     cadOK.setLocationRelativeTo(null);
     cadOK.setVisible(true);
     return cadProd.getProdutoView();  

 }
 
 public void showError(){
     
     ErrLogin err = new ErrLogin();
    
    err.setLocationRelativeTo(null);
    err.setVisible(true);
 
     
 }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
